# Do NOT update manually; changes here will be overwritten by Copier
_commit: c26a26c
_src_path: https://github.com/open-synergy/ssi-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: ssi-py3o
repo_name: Extra tool and funcionalities for py3o reporting engine
repo_slug: ssi-py3o
travis_apt_packages: []
travis_apt_sources: []

