# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
"""Every method here is pure Python -- trigger P1 (L-01: ``action: call``
in odoo-yaml-test discards the method's return value, and
``_get_html_text`` is exactly that: a method whose string/``Markup``
return value is what is being asserted, not a side effect on a
record). See the skill odoo-development-unit-test,
references/python-escape-hatch.md.
"""
import re

from genshi.core import Markup
from odoo_yaml_test import YamlTransactionCase

from odoo.tests import tagged


@tagged("post_install", "-at_install")
class TestHtmlText(YamlTransactionCase):
    """Cover ``py3o.report._get_html_text`` (Html field -> ODF markup)."""

    def setUp(self):
        """Bind an empty ``py3o.report`` recordset to call the method on.

        None of the ``_get_html_text*`` helpers read ``self`` — an
        empty recordset is enough to call them, same pattern as
        ``TestOdfMerge`` in ``test_odf_merge.py``.
        """
        super().setUp()
        self.engine = self.env["py3o.report"]

    def test_bold_from_style_attribute(self):
        """Detect Bold from ``style="font-weight: bolder"``.

        This is the bug reported in HT/26/000756: the old ad-hoc
        parser only recognised the ``<b>``/``<strong>`` tags, not the
        ``style`` attribute that the Odoo Html editor actually emits.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = self.engine._get_html_text(
            '<p><span style="font-weight: bolder;">Context</span> ' "teks biasa</p>"
        )
        self.assertIsInstance(result, Markup)
        self.assertIn(
            '<text:span text:style-name="Bold">Context</text:span>',
            str(result),
        )
        self.assertIn("Context</text:span> teks biasa", str(result))
        self.assertNotIn("<text:p>", str(result))

    def test_bold_italic_underline_from_semantic_tags(self):
        """Keep detecting Bold/Italic/Underline from semantic tags.

        Guards against a regression while fixing the ``style``
        attribute detection above.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text("<b>Bold</b> <i>Italic</i> <u>Underline</u>")
        )
        self.assertIn('<text:span text:style-name="Bold">Bold</text:span>', result)
        self.assertIn('<text:span text:style-name="Italic">Italic</text:span>', result)
        self.assertIn(
            '<text:span text:style-name="Underline">Underline</text:span>',
            result,
        )

    def test_unordered_list_bullets(self):
        """Render ``<ul><li>`` items as a genuine ``OdooUL`` ODF list.

        Each item is its own ``<text:list-item>``/``OdooListItem``-styled
        ``<text:p>`` inside one shared ``<text:list>`` -- no bullet
        character is written into the text: it's generated by the
        renderer from the ``OdooUL`` list style
        (``_py3o_append_list_style``), the same way it computes a
        wrapped continuation line's hang indent against that marker
        (see ``_HTML_LIST_ITEM_INDENT``'s comment for why a
        fixed-guess indent, tried first, didn't hold up).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<ul><li>A</li><li>B</li></ul>"))
        self.assertEqual(
            result,
            "</text:span></text:p>"
            '<text:list text:style-name="OdooUL">'
            '<text:list-item><text:p text:style-name="OdooListItem">A</text:p>'
            "</text:list-item>"
            '<text:list-item><text:p text:style-name="OdooListItem">B</text:p>'
            "</text:list-item>"
            "</text:list>"
            "<text:p><text:span>",
        )

    def test_ordered_list_numbers(self):
        """Render ``<ol><li>`` items as a genuine ``OdooOL`` ODF list.

        No ``1.``/``2.`` prefix is written into the text -- that
        numbering is generated by the renderer from the ``OdooOL``
        list style, not baked into the content here (see
        ``test_unordered_list_bullets``).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<ol><li>A</li><li>B</li></ol>"))
        self.assertIn('<text:list text:style-name="OdooOL">', result)
        self.assertNotIn("1.", result)
        self.assertLess(result.index(">A<"), result.index(">B<"))

    def test_list_item_wrap_point_not_inserted_mid_marker(self):
        """Batch consecutive ``<li>``\\ s so no stray blank line lands between them.

        Regression guard: emitting one close/reopen escape per ``<li>``
        instead of one per run of consecutive ``<li>``\\ s would leave a
        ``<text:line-break/>`` from ``_get_html_text``'s block-joining
        stranded inside an otherwise-empty paragraph between every pair
        of items.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text("<ul><li>A</li><li>B</li><li>C</li></ul>")
        )
        self.assertNotIn("<text:line-break/>", result)
        self.assertEqual(result.count("OdooListItem"), 3)

    def test_empty_input_returns_empty_markup(self):
        """Return ``Markup("")`` for ``False``/blank Html values.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        self.assertEqual(self.engine._get_html_text(False), Markup(""))
        self.assertEqual(self.engine._get_html_text("   "), Markup(""))

    def test_long_unbroken_run_gets_wrap_points(self):
        """Break a long spaceless run with invisible zero-width spaces.

        Regression guard: a long unbroken token (e.g. pasted text with
        no spaces) has no natural word-wrap point, forcing
        LibreOffice's PDF export into a character-level forced-wrap
        fallback for that one line -- confirmed (against Atril/MATE's
        poppler-based viewer) to make some renderers mis-compute that
        line's height and visually overlap the next line. Inserting a
        zero-width space every 20 characters gives it normal
        word-wrap points instead.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>%s</p>" % ("a" * 45)))
        self.assertEqual(result, "​".join(["a" * 20, "a" * 20, "a" * 5]))

    def test_short_text_has_no_wrap_points_inserted(self):
        """Leave ordinary text (no run this long) untouched.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>kata biasa tidak diubah</p>"))
        self.assertNotIn("​", result)
        self.assertEqual(result, "kata biasa tidak diubah")

    def test_heading_uses_its_own_font_size_style(self):
        """Give each ``<h1>``-``<h6>`` its own font-size style, not Bold.

        Regression guard: headings used to be rendered by passing
        ``bold=True`` into the run builder, giving every level the
        exact same look (Bold only, no size difference).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<h1>Title</h1>"))
        self.assertEqual(
            result, '<text:span text:style-name="OdooH1">Title</text:span>'
        )

    def test_heading_levels_use_different_styles(self):
        """Give ``<h1>`` and ``<h6>`` distinct style names.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        h1 = str(self.engine._get_html_text("<h1>A</h1>"))
        h6 = str(self.engine._get_html_text("<h6>A</h6>"))
        self.assertIn("OdooH1", h1)
        self.assertIn("OdooH6", h6)
        self.assertNotEqual(h1, h6)

    def test_color_keyword_resolves_to_registered_style(self):
        """Resolve ``style="color: red"`` to the pre-registered style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<span style="color: red;">X</span>'))
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_color_hex_matching_a_keyword_resolves_the_same_way(self):
        """Resolve a hex color equal to a known keyword's hex value.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text('<span style="color: #FF0000;">X</span>')
        )
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_font_color_attribute_is_recognized(self):
        """Resolve the legacy ``<font color="...">`` attribute too.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<font color="red">X</font>'))
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_unregistered_color_renders_without_color(self):
        """Fall back to plain text for a color outside the fixed set.

        ODF text runs can only reference an already-declared style
        (see ``_py3o_ensure_html_text_styles``), so an arbitrary hex
        not equal to one of the 16 registered keywords cannot be
        supported -- it must render without color, not raise or
        reference a style that does not exist.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text('<span style="color: #123456;">X</span>')
        )
        self.assertEqual(result, "X")

    def test_heading_and_color_combine(self):
        """Nest a heading's colored text as color-inside-heading.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<h2 style="color: blue;">Title</h2>'))
        self.assertEqual(
            result,
            '<text:span text:style-name="OdooH2">'
            '<text:span text:style-name="OdooColor_0000ff">Title</text:span>'
            "</text:span>",
        )

    def test_heading_font_size_override_uses_combined_style(self):
        """A heading's own inline ``font-size`` gets one combined style.

        Regression guard for the bug found in the get_html_text
        heading feature: an author who types a heading then manually
        shrinks its font size (e.g. via the Odoo Html editor's font
        size control) expects that shrink to survive into the printed
        report, not be silently replaced by the heading's own preset
        size (24pt down to 10pt). A plain nested ``text:span`` override
        was tried first and found unreliable against this pipeline's
        actual LibreOffice conversion (it lost to the heading's preset
        size regardless of nesting order in some cases), so this
        asserts the combined-style approach that replaced it.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<h1><font style="font-size: 12px;">Title</font></h1>'
            )
        )
        self.assertEqual(
            result,
            '<text:span text:style-name="OdooH1_OdooFontSize_9">Title</text:span>',
        )

    def test_plain_font_size_override_outside_heading(self):
        """A ``font-size`` override outside any heading uses a standalone style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p><span style="font-size: 18px;">Big</span></p>'
            )
        )
        self.assertEqual(
            result, '<text:span text:style-name="OdooFontSize_13_5">Big</text:span>'
        )

    def test_get_html_text_font_sizes_splits_heading_and_plain(self):
        """Split ``font-size`` occurrences by whether they sit inside a heading.

        The scanning half of the font-size fix: ``_get_html_text``
        itself only resolves a size found *while walking one element*,
        so this method (used by ``_py3o_collect_html_font_sizes`` to
        pre-register styles, see ``get_template``) has to separately
        walk the whole value up front to know which sizes will turn up
        inside a heading versus outside one.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text_font_sizes``, not a record side effect).
        """
        plain_sizes, heading_sizes = self.engine._get_html_text_font_sizes(
            '<h2><font style="font-size: 12px;">S</font></h2>'
            '<p><span style="font-size: 18px;">Big</span></p>'
        )
        self.assertEqual(plain_sizes, {13.5})
        self.assertEqual(heading_sizes, {("OdooH2", 9.0)})

    def test_get_html_text_font_sizes_empty_for_blank_value(self):
        """Return two empty sets for a falsy/blank Html value.

        Pure Python -- trigger P1 (L-01: same reasoning as
        ``test_get_html_text_font_sizes_splits_heading_and_plain``).
        """
        self.assertEqual(self.engine._get_html_text_font_sizes(False), (set(), set()))
        self.assertEqual(self.engine._get_html_text_font_sizes(""), (set(), set()))

    def test_px_or_pt_to_pt_rounds_to_nearest_half_point(self):
        """Convert px to pt at 0.75pt/px, rounded to the nearest 0.5pt.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_px_or_pt_to_pt``, not a record side effect).
        """
        self.assertEqual(self.engine._px_or_pt_to_pt(12, "px"), 9.0)
        self.assertEqual(self.engine._px_or_pt_to_pt(10, "pt"), 10.0)
        self.assertEqual(self.engine._px_or_pt_to_pt(11.8, "px"), 9.0)

    def test_whitespace_only_paragraph_adds_no_line(self):
        """Drop a stray whitespace-only ``<p>`` between two paragraphs.

        Such paragraphs are a common paste artifact in the Odoo Html
        editor; the browser collapses them to ~0 height, so they must
        not add a line break here either (HT/26/000770-style regression
        guard: they were previously inflating paragraph spacing).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>A</p><p>\n\t\n</p><p>B</p>"))
        self.assertEqual(result, "A<text:line-break/>B")

    def test_br_only_paragraph_adds_exactly_one_blank_line(self):
        """Render a ``<p><br></p>`` as exactly one blank line.

        Not two: the paragraph's own ``<br>`` and the normal join
        break between paragraphs must not both count, or a single
        deliberate blank line renders as two.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>A</p><p><br></p><p>B</p>"))
        self.assertEqual(result, "A<text:line-break/><text:line-break/>B")

    def test_table_renders_as_real_odf_table(self):
        """Render ``<table>`` as a genuine nested ``<table:table>``.

        The surrounding ``<text:p>`` is closed before the table and
        reopened (empty) after it -- see ``_get_html_text_table`` for
        why that is the correct escape sequence here. ``<th>`` cells
        render Bold; row/cell counts match the source HTML.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<table><tr><th>Col 1</th><th>Col 2</th></tr>"
                "<tr><td>A</td><td><i>B</i></td></tr></table>"
            )
        )
        self.assertIn("</text:span></text:p><table:table", result)
        self.assertIn("</table:table><text:p><text:span>", result)
        self.assertEqual(result.count("<table:table-row>"), 2)
        self.assertEqual(result.count("<table:table-column/>"), 2)
        self.assertIn('<text:span text:style-name="Bold">Col 1</text:span>', result)
        self.assertIn(
            '<text:p text:style-name="OdooHtmlTableText">'
            '<text:span text:style-name="Italic">B</text:span></text:p>',
            result,
        )
        self.assertLess(result.index("Col 1"), result.index(">A<"))

    def test_table_name_is_unique_across_calls(self):
        """Give each rendered table a unique ``table:name``.

        ODF requires unique table names within one document; a report
        that calls ``get_html_text`` more than once (e.g. inside a
        ``py3o://for=`` loop) must not collide.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        first = str(self.engine._get_html_text("<table><tr><td>A</td></tr></table>"))
        second = str(self.engine._get_html_text("<table><tr><td>B</td></tr></table>"))
        name_re = re.compile(r'table:name="([^"]+)"')
        self.assertNotEqual(
            name_re.search(first).group(1), name_re.search(second).group(1)
        )

    def test_thead_rows_wrapped_for_page_repeat(self):
        """Wrap ``<thead>`` rows in ``<table:table-header-rows>``.

        So a renderer repeats the header row on every page a long
        table spans, instead of each page fragment showing bare
        bordered cells with no header -- which reads as two
        disconnected tables rather than one continuing table.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<table><thead><tr><th>Col 1</th></tr></thead>"
                "<tbody><tr><td>A</td></tr><tr><td>B</td></tr></tbody></table>"
            )
        )
        self.assertIn("<table:table-header-rows><table:table-row>", result)
        header_end = result.index("</table:table-header-rows>")
        self.assertLess(result.index("Col 1"), header_end)
        self.assertGreater(result.index(">A<"), header_end)
        self.assertGreater(result.index(">B<"), header_end)

    def test_table_without_thead_has_no_header_rows_wrapper(self):
        """Leave a plain ``<table>`` (no ``<thead>``) unaffected.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<table><tr><td>A</td></tr></table>"))
        self.assertNotIn("table-header-rows", result)

    def test_unknown_tag_falls_back_to_plain_text(self):
        """Render unsupported tags as plain text instead of raising.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<mark>teks</mark>"))
        self.assertIn("teks", result)
