# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
"""Every method here is pure Python -- trigger P1 (L-01: ``action: call``
in odoo-yaml-test discards the method's return value, and
``_get_html_text`` is exactly that: a method whose string/``Markup``
return value is what is being asserted, not a side effect on a
record). See the skill odoo-development-unit-test,
references/python-escape-hatch.md.
"""
import re

from genshi.core import Markup
from lxml import etree
from odoo_yaml_test import YamlTransactionCase

from odoo.tests import tagged


@tagged("post_install", "-at_install")
class TestHtmlText(YamlTransactionCase):
    """Cover ``py3o.report._get_html_text`` (Html field -> ODF markup)."""

    def setUp(self):
        """Bind an empty ``py3o.report`` recordset to call the method on.

        None of the ``_get_html_text*`` helpers read ``self`` — an
        empty recordset is enough to call them, same pattern as
        ``TestOdfMerge`` in ``test_odf_merge.py``.
        """
        super().setUp()
        self.engine = self.env["py3o.report"]

    def test_bold_from_style_attribute(self):
        """Detect Bold from ``style="font-weight: bolder"``.

        This is the bug reported in HT/26/000756: the old ad-hoc
        parser only recognised the ``<b>``/``<strong>`` tags, not the
        ``style`` attribute that the Odoo Html editor actually emits.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = self.engine._get_html_text(
            '<p><span style="font-weight: bolder;">Context</span> ' "teks biasa</p>"
        )
        self.assertIsInstance(result, Markup)
        self.assertIn(
            '<text:span text:style-name="Bold">Context</text:span>',
            str(result),
        )
        self.assertIn("Context</text:span> teks biasa", str(result))
        self.assertNotIn("<text:p>", str(result))

    def test_bold_italic_underline_from_semantic_tags(self):
        """Keep detecting Bold/Italic/Underline from semantic tags.

        Guards against a regression while fixing the ``style``
        attribute detection above.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text("<b>Bold</b> <i>Italic</i> <u>Underline</u>")
        )
        self.assertIn('<text:span text:style-name="Bold">Bold</text:span>', result)
        self.assertIn('<text:span text:style-name="Italic">Italic</text:span>', result)
        self.assertIn(
            '<text:span text:style-name="Underline">Underline</text:span>',
            result,
        )

    def test_unordered_list_bullets(self):
        """Render ``<ul><li>`` items as a genuine ``OdooUL`` ODF list.

        Each item is its own ``<text:list-item>``/``OdooListItem``-styled
        ``<text:p>`` inside one shared ``<text:list>`` -- no bullet
        character is written into the text: it's generated by the
        renderer from the ``OdooUL`` list style
        (``_py3o_append_list_style``), the same way it computes a
        wrapped continuation line's hang indent against that marker
        (see ``_HTML_LIST_ITEM_INDENT``'s comment for why a
        fixed-guess indent, tried first, didn't hold up).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<ul><li>A</li><li>B</li></ul>"))
        self.assertEqual(
            result,
            "</text:span></text:p>"
            '<text:list text:style-name="OdooUL">'
            '<text:list-item><text:p text:style-name="OdooListItem">A</text:p>'
            "</text:list-item>"
            '<text:list-item><text:p text:style-name="OdooListItem">B</text:p>'
            "</text:list-item>"
            "</text:list>"
            "<text:p><text:span>",
        )

    def test_ordered_list_numbers(self):
        """Render ``<ol><li>`` items as a genuine ``OdooOL`` ODF list.

        No ``1.``/``2.`` prefix is written into the text -- that
        numbering is generated by the renderer from the ``OdooOL``
        list style, not baked into the content here (see
        ``test_unordered_list_bullets``).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<ol><li>A</li><li>B</li></ol>"))
        self.assertIn('<text:list text:style-name="OdooOL">', result)
        self.assertNotIn("1.", result)
        self.assertLess(result.index(">A<"), result.index(">B<"))

    def test_list_item_wrap_point_not_inserted_mid_marker(self):
        """Batch consecutive ``<li>``\\ s so no stray blank line lands between them.

        Regression guard: emitting one close/reopen escape per ``<li>``
        instead of one per run of consecutive ``<li>``\\ s would leave a
        ``<text:line-break/>`` from ``_get_html_text``'s block-joining
        stranded inside an otherwise-empty paragraph between every pair
        of items.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text("<ul><li>A</li><li>B</li><li>C</li></ul>")
        )
        self.assertNotIn("<text:line-break/>", result)
        self.assertEqual(result.count("OdooListItem"), 3)

    def test_empty_input_returns_empty_markup(self):
        """Return ``Markup("")`` for ``False``/blank Html values.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        self.assertEqual(self.engine._get_html_text(False), Markup(""))
        self.assertEqual(self.engine._get_html_text("   "), Markup(""))

    def test_long_unbroken_run_gets_wrap_points(self):
        """Break a long spaceless run with invisible zero-width spaces.

        Regression guard: a long unbroken token (e.g. pasted text with
        no spaces) has no natural word-wrap point, forcing
        LibreOffice's PDF export into a character-level forced-wrap
        fallback for that one line -- confirmed (against Atril/MATE's
        poppler-based viewer) to make some renderers mis-compute that
        line's height and visually overlap the next line. Inserting a
        zero-width space every 20 characters gives it normal
        word-wrap points instead.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>%s</p>" % ("a" * 45)))
        self.assertEqual(result, "​".join(["a" * 20, "a" * 20, "a" * 5]))

    def test_short_text_has_no_wrap_points_inserted(self):
        """Leave ordinary text (no run this long) untouched.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>kata biasa tidak diubah</p>"))
        self.assertNotIn("​", result)
        self.assertEqual(result, "kata biasa tidak diubah")

    def test_heading_uses_its_own_font_size_style(self):
        """Give each ``<h1>``-``<h6>`` its own font-size style, not Bold.

        Regression guard: headings used to be rendered by passing
        ``bold=True`` into the run builder, giving every level the
        exact same look (Bold only, no size difference).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<h1>Title</h1>"))
        self.assertEqual(
            result, '<text:span text:style-name="OdooH1">Title</text:span>'
        )

    def test_heading_levels_use_different_styles(self):
        """Give ``<h1>`` and ``<h6>`` distinct style names.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        h1 = str(self.engine._get_html_text("<h1>A</h1>"))
        h6 = str(self.engine._get_html_text("<h6>A</h6>"))
        self.assertIn("OdooH1", h1)
        self.assertIn("OdooH6", h6)
        self.assertNotEqual(h1, h6)

    def test_color_keyword_resolves_to_registered_style(self):
        """Resolve ``style="color: red"`` to the pre-registered style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<span style="color: red;">X</span>'))
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_color_hex_matching_a_keyword_resolves_the_same_way(self):
        """Resolve a hex color equal to a known keyword's hex value.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text('<span style="color: #FF0000;">X</span>')
        )
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_font_color_attribute_is_recognized(self):
        """Resolve the legacy ``<font color="...">`` attribute too.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<font color="red">X</font>'))
        self.assertEqual(
            result, '<text:span text:style-name="OdooColor_ff0000">X</text:span>'
        )

    def test_unregistered_color_renders_without_color(self):
        """Fall back to plain text for a color outside the fixed set.

        ODF text runs can only reference an already-declared style
        (see ``_py3o_ensure_html_text_styles``), so an arbitrary hex
        not equal to one of the 16 registered keywords cannot be
        supported -- it must render without color, not raise or
        reference a style that does not exist.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text('<span style="color: #123456;">X</span>')
        )
        self.assertEqual(result, "X")

    def test_heading_and_color_combine(self):
        """Nest a heading's colored text as color-inside-heading.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text('<h2 style="color: blue;">Title</h2>'))
        self.assertEqual(
            result,
            '<text:span text:style-name="OdooH2">'
            '<text:span text:style-name="OdooColor_0000ff">Title</text:span>'
            "</text:span>",
        )

    def test_heading_font_size_override_uses_combined_style(self):
        """A heading's own inline ``font-size`` gets one combined style.

        Regression guard for the bug found in the get_html_text
        heading feature: an author who types a heading then manually
        shrinks its font size (e.g. via the Odoo Html editor's font
        size control) expects that shrink to survive into the printed
        report, not be silently replaced by the heading's own preset
        size (24pt down to 10pt). A plain nested ``text:span`` override
        was tried first and found unreliable against this pipeline's
        actual LibreOffice conversion (it lost to the heading's preset
        size regardless of nesting order in some cases), so this
        asserts the combined-style approach that replaced it.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<h1><font style="font-size: 12px;">Title</font></h1>'
            )
        )
        self.assertEqual(
            result,
            '<text:span text:style-name="OdooH1_OdooFontSize_9">Title</text:span>',
        )

    def test_plain_font_size_override_outside_heading(self):
        """A ``font-size`` override outside any heading uses a standalone style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p><span style="font-size: 18px;">Big</span></p>'
            )
        )
        self.assertEqual(
            result, '<text:span text:style-name="OdooFontSize_13_5">Big</text:span>'
        )

    def test_get_html_text_font_sizes_splits_heading_and_plain(self):
        """Split ``font-size`` occurrences by whether they sit inside a heading.

        The scanning half of the font-size fix: ``_get_html_text``
        itself only resolves a size found *while walking one element*,
        so this method (used by ``_py3o_collect_html_font_sizes`` to
        pre-register styles, see ``get_template``) has to separately
        walk the whole value up front to know which sizes will turn up
        inside a heading versus outside one.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text_font_sizes``, not a record side effect).
        """
        plain_sizes, heading_sizes = self.engine._get_html_text_font_sizes(
            '<h2><font style="font-size: 12px;">S</font></h2>'
            '<p><span style="font-size: 18px;">Big</span></p>'
        )
        self.assertEqual(plain_sizes, {13.5})
        self.assertEqual(heading_sizes, {("OdooH2", 9.0)})

    def test_get_html_text_font_sizes_empty_for_blank_value(self):
        """Return two empty sets for a falsy/blank Html value.

        Pure Python -- trigger P1 (L-01: same reasoning as
        ``test_get_html_text_font_sizes_splits_heading_and_plain``).
        """
        self.assertEqual(self.engine._get_html_text_font_sizes(False), (set(), set()))
        self.assertEqual(self.engine._get_html_text_font_sizes(""), (set(), set()))

    def test_px_or_pt_to_pt_rounds_to_nearest_half_point(self):
        """Convert px to pt at 0.75pt/px, rounded to the nearest 0.5pt.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_px_or_pt_to_pt``, not a record side effect).
        """
        self.assertEqual(self.engine._px_or_pt_to_pt(12, "px"), 9.0)
        self.assertEqual(self.engine._px_or_pt_to_pt(10, "pt"), 10.0)
        self.assertEqual(self.engine._px_or_pt_to_pt(11.8, "px"), 9.0)

    def test_whitespace_only_paragraph_adds_no_line(self):
        """Drop a stray whitespace-only ``<p>`` between two paragraphs.

        Such paragraphs are a common paste artifact in the Odoo Html
        editor; the browser collapses them to ~0 height, so they must
        not add a line break here either (HT/26/000770-style regression
        guard: they were previously inflating paragraph spacing).

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>A</p><p>\n\t\n</p><p>B</p>"))
        self.assertEqual(result, "A<text:line-break/>B")

    def test_br_only_paragraph_adds_exactly_one_blank_line(self):
        """Render a ``<p><br></p>`` as exactly one blank line.

        Not two: the paragraph's own ``<br>`` and the normal join
        break between paragraphs must not both count, or a single
        deliberate blank line renders as two.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>A</p><p><br></p><p>B</p>"))
        self.assertEqual(result, "A<text:line-break/><text:line-break/>B")

    def test_table_renders_as_real_odf_table(self):
        """Render ``<table>`` as a genuine nested ``<table:table>``.

        The surrounding ``<text:p>`` is closed before the table and
        reopened (empty) after it -- see ``_get_html_text_table`` for
        why that is the correct escape sequence here. ``<th>`` cells
        render Bold; row/cell counts match the source HTML.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<table><tr><th>Col 1</th><th>Col 2</th></tr>"
                "<tr><td>A</td><td><i>B</i></td></tr></table>"
            )
        )
        self.assertIn("</text:span></text:p><table:table", result)
        self.assertIn("</table:table><text:p><text:span>", result)
        self.assertEqual(result.count("<table:table-row>"), 2)
        self.assertEqual(result.count("<table:table-column/>"), 2)
        self.assertIn('<text:span text:style-name="Bold">Col 1</text:span>', result)
        self.assertIn(
            '<text:p text:style-name="OdooHtmlTableText">'
            '<text:span text:style-name="Italic">B</text:span></text:p>',
            result,
        )
        self.assertLess(result.index("Col 1"), result.index(">A<"))

    def test_table_name_is_unique_across_calls(self):
        """Give each rendered table a unique ``table:name``.

        ODF requires unique table names within one document; a report
        that calls ``get_html_text`` more than once (e.g. inside a
        ``py3o://for=`` loop) must not collide.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        first = str(self.engine._get_html_text("<table><tr><td>A</td></tr></table>"))
        second = str(self.engine._get_html_text("<table><tr><td>B</td></tr></table>"))
        name_re = re.compile(r'table:name="([^"]+)"')
        self.assertNotEqual(
            name_re.search(first).group(1), name_re.search(second).group(1)
        )

    def test_thead_rows_wrapped_for_page_repeat(self):
        """Wrap ``<thead>`` rows in ``<table:table-header-rows>``.

        So a renderer repeats the header row on every page a long
        table spans, instead of each page fragment showing bare
        bordered cells with no header -- which reads as two
        disconnected tables rather than one continuing table.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<table><thead><tr><th>Col 1</th></tr></thead>"
                "<tbody><tr><td>A</td></tr><tr><td>B</td></tr></tbody></table>"
            )
        )
        self.assertIn("<table:table-header-rows><table:table-row>", result)
        header_end = result.index("</table:table-header-rows>")
        self.assertLess(result.index("Col 1"), header_end)
        self.assertGreater(result.index(">A<"), header_end)
        self.assertGreater(result.index(">B<"), header_end)

    def test_table_without_thead_has_no_header_rows_wrapper(self):
        """Leave a plain ``<table>`` (no ``<thead>``) unaffected.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<table><tr><td>A</td></tr></table>"))
        self.assertNotIn("table-header-rows", result)

    def test_unknown_tag_falls_back_to_plain_text(self):
        """Render unsupported tags as plain text instead of raising.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<mark>teks</mark>"))
        self.assertIn("teks", result)

    # -- paragraph alignment (text-align / align) ---------------------------

    def _style_names(self, markup):
        """Return every ``text:style-name`` value in ``markup``, in order."""
        return re.findall(r'text:style-name="([^"]+)"', str(markup))

    def test_alignment_values_map_to_paragraph_styles(self):
        """Emit a paragraph of its own styled per alignment.

        left/start, center, right/end and justify each select their
        own ``OdooHtmlAlign*`` automatic style. The block closes the
        template's paragraph (the escape used for tables and lists) and,
        being last, leaves its own paragraph open for the template's
        closing tags to end, so no empty paragraph trails it.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        expected = {
            "left": "OdooHtmlAlignStart",
            "start": "OdooHtmlAlignStart",
            "center": "OdooHtmlAlignCenter",
            "right": "OdooHtmlAlignEnd",
            "end": "OdooHtmlAlignEnd",
            "justify": "OdooHtmlAlignJustify",
        }
        for value, style_name in expected.items():
            with self.subTest(value=value):
                result = str(
                    self.engine._get_html_text(
                        '<p style="text-align: %s">teks</p>' % value
                    )
                )
                self.assertEqual(
                    result,
                    '</text:span></text:p><text:p text:style-name="%s">teks'
                    "<text:span>" % style_name,
                )

    def test_alignment_ignores_case_and_spacing(self):
        """Read ``TEXT-ALIGN :JUSTIFY`` the same as ``text-align: justify``.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = self.engine._get_html_text('<p style="TEXT-ALIGN :JUSTIFY">x</p>')
        self.assertEqual(self._style_names(result), ["OdooHtmlAlignJustify"])

    def test_align_attribute_and_style_precedence(self):
        """Honour the legacy ``align`` attribute; ``style`` wins over it.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        only_attr = self.engine._get_html_text('<p align="center">x</p>')
        self.assertEqual(self._style_names(only_attr), ["OdooHtmlAlignCenter"])
        both = self.engine._get_html_text(
            '<p style="text-align: right" align="center">x</p>'
        )
        self.assertEqual(self._style_names(both), ["OdooHtmlAlignEnd"])

    def test_aligned_block_is_split_at_br(self):
        """Turn ``<p>title<br>body</p>`` into two aligned paragraphs.

        A manual line break inside a justified paragraph would make
        LibreOffice stretch the line it ends, so the title must not
        share a paragraph with the body.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p style="text-align: justify"><b>Judul</b><br>Isi</p>'
            )
        )
        self.assertEqual(result.count("<text:p text:style-name="), 2)
        self.assertNotIn("<text:line-break/>", result)
        self.assertLess(result.index("Judul"), result.index("Isi"))

    def test_aligned_block_keeps_inline_formatting(self):
        """Keep bold/italic/underline/color/size inside an aligned paragraph.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        inner = (
            '<b>B</b> <i>I</i> <u>U</u> <span style="color: red; '
            'font-size: 14px">C</span>'
        )
        plain = str(self.engine._get_html_text("<p>%s</p>" % inner))
        aligned = str(
            self.engine._get_html_text('<p style="text-align: justify">%s</p>' % inner)
        )
        self.assertIn(plain, aligned)

    def test_aligned_heading(self):
        """Align a heading and keep its heading style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = self.engine._get_html_text('<h2 style="text-align: center">Judul</h2>')
        self.assertEqual(self._style_names(result)[0], "OdooHtmlAlignCenter")
        self.assertIn("OdooH2", self._style_names(result))

    def test_base_style_selects_wrapper_specific_style(self):
        """Use the wrapper paragraph's own alignment style when given.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = self.engine._get_html_text(
            '<p style="text-align: justify">x</p>', base_style="P7"
        )
        self.assertEqual(self._style_names(result), ["OdooHtmlAlignJustify_P7"])

    def test_aligned_paragraph_next_to_table_and_list(self):
        """Leave a table and a list beside aligned paragraphs untouched.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        table_html = "<table><tr><td>t</td></tr></table>"
        list_html = "<ul><li>x</li></ul>"
        plain = str(self.engine._get_html_text(table_html + list_html))
        aligned = str(
            self.engine._get_html_text(
                '<p style="text-align: justify">a</p>'
                + table_html
                + list_html
                + '<p style="text-align: center">b</p>'
            )
        )
        self.assertEqual(aligned.count("<table:table "), plain.count("<table:table "))
        self.assertEqual(aligned.count("<text:list "), plain.count("<text:list "))
        self.assertNotIn("<text:line-break/>", aligned)

    def test_html_without_alignment_is_unchanged(self):
        """Render HTML with no alignment exactly as before.

        Covers plain paragraphs, a ``text-align`` that sits only on a
        ``<span>``, an unknown value, a ``<li>`` and a table.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        samples = [
            "<p>kata biasa</p>",
            "<p>satu</p><p>dua</p>",
            '<p><span style="text-align: justify">T</span><br><span>B</span></p>',
            '<p style="text-align: foo">x</p>',
            '<p style="margin: 0">x</p>',
            "<ul><li>A</li></ul>",
        ]
        for html_value in samples:
            with self.subTest(html=html_value):
                result = str(self.engine._get_html_text(html_value))
                self.assertNotIn("OdooHtmlAlign", result)
        self.assertEqual(
            str(self.engine._get_html_text("<p>satu</p><p>dua</p>")),
            "satu<text:line-break/>dua",
        )

    def test_consecutive_aligned_blocks_leave_no_empty_paragraph(self):
        """Put aligned paragraphs back to back with nothing between them.

        Joining two escaped blocks the usual way would leave an empty
        ``<text:p>`` -- a visible blank line -- between every pair of
        aligned paragraphs.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p style="text-align: justify">a</p>'
                '<p style="text-align: justify"></p>'
                '<p style="text-align: center">b</p>'
                '<p style="text-align: right">c</p>'
            )
        )
        self.assertEqual(
            result,
            '</text:span></text:p><text:p text:style-name="OdooHtmlAlignJustify">a'
            '</text:p><text:p text:style-name="OdooHtmlAlignCenter">b'
            '</text:p><text:p text:style-name="OdooHtmlAlignEnd">c<text:span>',
        )
        self.assertNotIn("<text:p><text:span>", result)

    def test_aligned_block_followed_by_plain_block(self):
        """Reopen the template paragraph for plain text after an aligned one.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p style="text-align: justify">a</p><p>polos</p>'
            )
        )
        self.assertTrue(result.endswith("</text:p><text:p><text:span>polos"))

    # -- CSS property names must match whole, not as a suffix ---------------

    def test_prefixed_css_properties_are_ignored(self):
        """Ignore Word/other properties that merely end like a known one.

        ``mso-bidi-font-weight:bold`` is not ``font-weight``,
        ``background-color`` is not ``color``, and so on: none of them
        may produce Bold, Italic, Underline, a color or a font size.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        prefixed = [
            "mso-bidi-font-weight:bold",
            "mso-bidi-font-style:italic",
            "mso-bidi-text-decoration:underline",
            "background-color: red",
            "border-color: red",
            "mso-ansi-font-size:20pt",
        ]
        for declaration in prefixed:
            with self.subTest(declaration=declaration):
                result = str(
                    self.engine._get_html_text(
                        '<p><span style="%s">x</span></p>' % declaration
                    )
                )
                self.assertNotIn("Bold", result)
                self.assertNotIn("Italic", result)
                self.assertNotIn("Underline", result)
                self.assertNotIn("OdooColor_", result)
                self.assertNotIn("OdooFontSize_", result)

    def test_valid_css_property_beside_prefixed_one(self):
        """Keep reading a real declaration written next to a prefixed one.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        not_bold = str(
            self.engine._get_html_text(
                '<p><span style="mso-bidi-font-weight:bold; '
                'font-weight: normal">x</span></p>'
            )
        )
        self.assertNotIn("Bold", not_bold)
        bold = str(
            self.engine._get_html_text(
                '<p><span style="mso-fareast-font-family:SimSun; '
                'font-weight: bold">x</span></p>'
            )
        )
        self.assertIn('text:style-name="Bold"', bold)
        mixed = str(
            self.engine._get_html_text(
                '<p><span style="background-color: blue; color: red; '
                'mso-ansi-font-size:20pt; font-size: 14px">x</span></p>'
            )
        )
        self.assertIn("OdooColor_ff0000", mixed)
        self.assertNotIn("OdooColor_0000ff", mixed)
        self.assertIn("OdooFontSize_10_5", mixed)
        self.assertNotIn("OdooFontSize_20", mixed)

    def test_css_property_recognised_at_start_after_space_and_semicolon(self):
        """Recognise a property at the start, after a space and after ``;``.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        for style in (
            "font-weight:bold",
            "margin: 0; font-weight:bold",
            "margin: 0;font-weight:bold",
        ):
            with self.subTest(style=style):
                result = str(
                    self.engine._get_html_text(
                        '<p><span style="%s">x</span></p>' % style
                    )
                )
                self.assertIn('text:style-name="Bold"', result)

    def test_list_items_use_base_style_variant(self):
        """Style every ``<ul>``/``<ol>`` item with the wrapper's variant.

        With ``base_style`` each item paragraph names the
        ``OdooListItem_<base_style>`` variant, never the fixed 8pt
        ``OdooListItem`` style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        for tag in ("ul", "ol"):
            with self.subTest(tag=tag):
                result = str(
                    self.engine._get_html_text(
                        "<%(t)s><li>a</li><li>b</li></%(t)s>" % {"t": tag},
                        base_style="P7",
                    )
                )
                self.assertEqual(
                    result.count('<text:p text:style-name="OdooListItem_P7">'), 2
                )
                self.assertNotIn('text:style-name="OdooListItem"', result)

    def test_paragraph_after_list_carries_base_style(self):
        """Reopen the paragraph after a list with the wrapper style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<ul><li>a</li></ul><p>sesudah</p>", base_style="P7"
            )
        )
        self.assertIn(
            '</text:list><text:p text:style-name="P7"><text:span>sesudah',
            result,
        )

    def test_paragraph_after_table_and_aligned_block_carries_base_style(self):
        """Reopen the paragraph after a table and an aligned paragraph.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        after_table = str(
            self.engine._get_html_text(
                "<table><tr><td>t</td></tr></table><p>sesudah</p>",
                base_style="P7",
            )
        )
        self.assertIn(
            '</table:table><text:p text:style-name="P7"><text:span>sesudah',
            after_table,
        )
        after_aligned = str(
            self.engine._get_html_text(
                '<p style="text-align: justify">a</p><p>sesudah</p>',
                base_style="P7",
            )
        )
        self.assertIn(
            '</text:p><text:p text:style-name="P7"><text:span>sesudah',
            after_aligned,
        )

    def test_no_base_style_output_is_unchanged(self):
        """Keep the fixed style and unstyled reopen without ``base_style``.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                "<ul><li>a</li></ul><p>x</p>"
                "<table><tr><td>t</td></tr></table><p>y</p>"
                '<p style="text-align: center">c</p><p>z</p>'
            )
        )
        self.assertIn('<text:p text:style-name="OdooListItem">', result)
        self.assertIn("</text:list><text:p><text:span>x", result)
        self.assertIn("</table:table><text:p><text:span>y", result)
        self.assertNotIn("OdooListItem_", result)
        self.assertNotIn("P7", result)

    def test_base_style_keeps_line_break_count(self):
        """Add no line break or empty paragraph when ``base_style`` is set.

        The count of ``<text:line-break/>`` and of empty reopened
        paragraphs is the same with and without ``base_style`` for a
        list, table and aligned paragraph in a row, and for a list
        that ends the content.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        samples = (
            "<p>a</p><ul><li>x</li></ul><p>b</p>"
            "<table><tr><td>t</td></tr></table>"
            '<p style="text-align: justify">c</p><p>d</p>',
            "<p>a</p><ul><li>x</li></ul>",
            '<ol><li>x</li></ol><p style="text-align: end">c</p>',
        )
        for html_value in samples:
            with self.subTest(html=html_value):
                plain = str(self.engine._get_html_text(html_value))
                styled = str(self.engine._get_html_text(html_value, base_style="P7"))
                self.assertEqual(
                    styled.count("<text:line-break/>"),
                    plain.count("<text:line-break/>"),
                )
                self.assertEqual(styled.count("<text:p"), plain.count("<text:p"))
                self.assertNotIn("<text:p><text:span>", styled)

    # -- #17: margins, indent, NBSP and Symbol bullets ---------------------

    def _margins(self, style):
        """Return the margin tuple read from a ``<p>`` with ``style``.

        :param style: value of the ``style`` attribute
        :return: tuple from ``_get_html_text_paragraph_margins``
        :rtype: tuple or None
        """
        el = etree.fromstring('<p style="%s">x</p>' % style)
        return self.engine._get_html_text_paragraph_margins(el)

    def _paragraph_style_props(self, odf_align, base_style, margins):
        """Build a paragraph style and return its ``fo:`` attributes.

        :param odf_align: ODF alignment or ``None``
        :param base_style: wrapper style name or ``None``
        :param margins: margin tuple
        :return: mapping of ``fo:`` attribute local names to values
        :rtype: dict
        """
        auto_styles = etree.Element(
            "{urn:oasis:names:tc:opendocument:xmlns:office:1.0}automatic-styles"
        )
        style = self.engine._py3o_html_align_style_element(
            auto_styles, odf_align, base_style, margins
        )
        props = style[0]
        prefix = "{urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0}"
        return {
            key[len(prefix) :]: value
            for key, value in props.attrib.items()
            if key.startswith(prefix)
        }

    def test_nbsp_runs_are_kept_and_ascii_spaces_collapse(self):
        """Keep U+00A0 runs while ASCII whitespace still collapses.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(self.engine._get_html_text("<p>a\u00a0\u00a0\u00a0b  c\n\td</p>"))
        self.assertIn("a\u00a0\u00a0\u00a0b c d", result)

    def test_paragraph_margins_become_own_paragraph_style(self):
        """Render a ``<p>`` with margins as a paragraph of its own.

        The style name encodes the values, and the built style holds
        left 16.5pt, indent -14.5pt and top 6pt.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p style="margin-left:16.55pt;text-indent:-14.4pt;'
                'margin-top:6pt">butir</p>',
                base_style="P7",
            )
        )
        name = "OdooHtmlAlignInherit_mt6_ml16_5_tin14_5_P7"
        self.assertIn('<text:p text:style-name="%s">butir</text:p>' % name, result)
        self.assertEqual(
            self._paragraph_style_props(None, "P7", (6.0, None, 16.5, None, -14.5)),
            {"margin-top": "6pt", "margin-left": "16.5pt", "text-indent": "-14.5pt"},
        )

    def test_length_units_are_converted_to_points(self):
        """Convert pt, px, cm, mm and in, rounded to 0.5pt.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text_paragraph_margins``, not a record side
        effect).
        """
        cases = {
            "margin-left:10pt": 10.0,
            "margin-left:20px": 15.0,
            "margin-left:1cm": 28.5,
            "margin-left:10mm": 28.5,
            "margin-left:0.5in": 36.0,
            "margin-left:16.55pt": 16.5,
            "text-indent:-14.4pt": -14.5,
        }
        for style, expected in cases.items():
            with self.subTest(style=style):
                margins = self._margins(style)
                self.assertEqual(
                    [value for value in margins if value is not None], [expected]
                )

    def test_margin_shorthand_with_one_to_four_values(self):
        """Expand the ``margin`` shorthand in CSS order.

        Tuple order is top, bottom, left, right, text-indent.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text_paragraph_margins``, not a record side
        effect).
        """
        self.assertEqual(self._margins("margin:6pt"), (6, 6, 6, 6, None))
        self.assertEqual(self._margins("margin:6pt 12pt"), (6, 6, 12, 12, None))
        self.assertEqual(self._margins("margin:6pt 12pt 18pt"), (6, 18, 12, 12, None))
        self.assertEqual(
            self._margins("margin:6pt 12pt 18pt 24pt"), (6, 18, 24, 12, None)
        )

    def test_margins_combine_with_text_align_in_one_style(self):
        """Give a justified paragraph with margins a single style.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        result = str(
            self.engine._get_html_text(
                '<p style="text-align:justify;margin-left:16.5pt">x</p>'
            )
        )
        self.assertEqual(result.count("<text:p text:style-name="), 2)
        self.assertIn('text:style-name="OdooHtmlAlignJustify_ml16_5">x', result)
        self.assertEqual(
            self._paragraph_style_props(
                "justify", None, (None, None, 16.5, None, None)
            ),
            {"text-align": "justify", "margin-left": "16.5pt"},
        )

    def test_symbol_font_marker_becomes_bullet(self):
        """Print U+00B7 and U+F0B7 in a Symbol font run as a bullet.

        The same characters outside a Symbol font are left alone.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        symbol = str(
            self.engine._get_html_text(
                '<p><span style="font-family:Symbol">\u00b7</span>'
                '<span style="mso-bidi-font-family:Symbol;font-family:Arial">'
                "\u00b7</span></p>"
            )
        )
        self.assertIn("\u2022", symbol)
        self.assertEqual(symbol.count("\u00b7"), 1)
        pua = str(
            self.engine._get_html_text(
                "<p style=\"font-family:'Symbol'\"><span>\uf0b7</span></p>"
            )
        )
        self.assertIn("\u2022", pua)

    def test_plain_paragraph_and_non_numeric_values_unchanged(self):
        """Leave plain output alone and honour an explicit zero.

        A ``<p>`` without the new properties, ``\u00b7`` outside a
        Symbol font and a non-numeric margin render as before;
        ``margin-bottom:0`` alone gives a zero bottom margin.

        Pure Python -- trigger P1 (L-01: asserting the return value
        of ``_get_html_text``, not a record side effect).
        """
        plain = str(self.engine._get_html_text("<p>a \u00b7 b</p>"))
        self.assertEqual(plain, "a \u00b7 b")
        self.assertIsNone(self._margins("margin-left:auto"))
        self.assertIsNone(self._margins("line-height:12pt"))
        self.assertEqual(
            self._margins("margin-bottom:0"), (None, 0.0, None, None, None)
        )
        zero = str(self.engine._get_html_text('<p style="margin-bottom:0cm">z</p>'))
        self.assertIn('text:style-name="OdooHtmlAlignInherit_mb0"', zero)
        self.assertEqual(
            self._paragraph_style_props(None, None, (None, 0.0, None, None, None)),
            {"margin-bottom": "0pt"},
        )
